# Generated by Django 6.0.1 on 2026-02-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.IntegerField(db_index=True, default=2000),
            preserve_default=False,
        ),
    ]
