# Generated by Django 6.0.1 on 2026-02-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='stripe_subscription_item_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
