# Generated by Django 6.0.1 on 2026-02-15 15:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_apikey_stripe_subscription_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='usage_reset_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
